/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { weathersGet } from "../../funcs/weathersGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetWeatherDataRequest$inboundSchema,
};

export const tool$weathersGet: ToolDefinition<typeof args> = {
  name: "weathers-get",
  description:
    `Retrieve current weather, hourly forecast, and daily forecast based on latitude and longitude.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await weathersGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
