/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Weathers } from "./weathers.js";

export class SpeakeasyWeatherSDK extends ClientSDK {
  private _weathers?: Weathers;
  get weathers(): Weathers {
    return (this._weathers ??= new Weathers(this._options));
  }
}
