/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { weathersGet } from "../funcs/weathersGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Weathers extends ClientSDK {
  /**
   * Retrieve current weather, hourly forecast, and daily forecast based on latitude and longitude.
   */
  async get(
    request: operations.GetWeatherDataRequest,
    options?: RequestOptions,
  ): Promise<components.WeatherResponse> {
    return unwrapAsync(weathersGet(
      this,
      request,
      options,
    ));
  }
}
